# Generated by Django 5.2.1 on 2025-05-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('tags', models.CharField(blank=True, max_length=50)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
